### ISSUE TITLE
init.el不起作用

### ISSUE THREAD

**Issue by vipzrx** [xyguo/emacs.d#1]
你好，我看了你的
Emacs配置文件——新手攻略 - 作业部落 Cmd Markdown 编辑阅读器
https://www.zybuluo.com/qqiseeu/note/17692
我想请教你一个问题，为什么我按照你的方法设置了init.el。里面的设置不起作用
你有邮箱吗？我的vipzrx T gmail

**Comment by xyguo** [comment]
你好，我的邮箱是xyguo.ubd@gmail.com，请把你的问题详细地描述一下，谢谢。
