### ISSUE TITLE
Symbol's function definition is void: advice-add

### ISSUE THREAD

**Issue by congleetea** [xyguo/emacs.d#2]
Hi , I meet a issue:
Warning (initialization): An error occurred while loading `/home/xxx/.emacs.d/init.el':

Symbol's function definition is void: advice-add

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

so when I start emacs with "emacs --debug-init", it shows 

Debugger entered--Lisp error: (void-function advice-add)
  advice-add(linum-update-current :after hlinum-highlight-line)
  hlinum-activate()
  eval-buffer(#<buffer  *load*-443356> nil "/home/xxx/.emacs.d/lisp/init-editing-utils.el" nil t)  ; Reading at buffer position 1637
  load-with-code-conversion("/home/xxx/.emacs.d/lisp/init-editing-utils.el" "/home/xxx/.emacs.d/lisp/init-editing-utils.el" nil t)
  require(init-editing-utils)
  eval-buffer(#<buffer  *load*> nil "/home/xx/.emacs.d/init.el" nil t)  ; Reading at buffer position 1733
  load-with-code-conversion("/home/xxx/.emacs.d/init.el" "/home/xxx/.emacs.d/init.el" t t)
  load("/home/xxx/.emacs.d/init" t t)
  #[0 "\205\262   \306=\203\307\310Q\202; \311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

can you help me for this problem ? thanks a lot.

**Comment by xyguo** [comment]
Could you give some system information? such as

```
$ uname -a
```

and also the emacs' version?
(in shell, type

```
$ emacs --version
```

or in Emacs, `M-x emacs-version`)

The `advice-add` is part of the [new advice system](http://emacs.stackexchange.com/q/3079/504) introduced in Emacs **24.4**, so if you're on Emacs 24.3 or older, you can't use it. 

In the Readme file of this repository it is said that "Emacs 24.3.1 or greater is ok", that's an obsolete requirement and I'll update it right away.

**Comment by congleetea** [comment]
Yes，version of my emacs is  24.3.  thank you very much. I will check it  with emacs 24.4.

**Comment by congleetea** [comment]
btw, the requirement of version of git should be 1.9.4 or greater.

**Comment by xyguo** [comment]
I'll update the README file accordingly, thank you.
