### ISSUE TITLE
error: Package `emacs-24.4' is unavailable

### ISSUE THREAD

**Issue by minghu6** [xyguo/emacs.d#3]
- x86 Ubuntu 12.04 
- emacs24.4

用clone的.emacs.d直接覆盖掉`~/.emacs.d`，第一次启动emacs时报错如标题。
导致`auto-complete` 似乎没法正常使用（ TAB键时，出现

 `Error running timer`ac-update-greedy': (error "Invalid argument 3 of operation `call-process-region'")`

请问需要修改哪里？（emacs小白请教）

**Comment by xyguo** [comment]
请在shell里用下述方法启动Emacs，然后把产生的stacktrace贴上来看看

```
emacs --debug-init
```

另外你的emacs是怎么安装的，自己从源码编译的？如果是用apt-get装的话不太可能是24.4版本的吧，ubuntu 12.04的源太老了，里面没有这个版本的emacs。

**Comment by minghu6** [comment]
并且
`emacs -version`
显示的版本居然是24.3

**Comment by minghu6** [comment]
是的，emacs与git的源版本都非常古老，我是手动安装的。
之前的问题是没有把apt-get安装的emacs 24.3卸载干净，虽然从源代码安装的是emacs24.5,，但仍然被认作是旧版本，通过find/ rm 手动删掉了旧版本的emacs以后，再从源代码重新安装顺利得到了新版本emacs(24.5),以后，emac启动就没问题了。

总而言之就是**旧版本emacs卸载不干净**导致的。

另外：
- 话说clang版本是·3.0-6·，没有达到README里的·3.2-10·，编辑C代码时用起来似乎也没问题。
-  用到现在，不知怎称呼,姑且 `xyguo`的配置确实不错，之前用过的另一位基于Purcell前辈的
  vim风格的emacs配置,就十分蛋疼，不如这个的配置品味强大却又简洁，低调而有内涵，真是不错，学习了！

**Comment by xyguo** [comment]
如果方便的话，建议把ubuntu升级一下吧，现在官方对12.04版本好像都已经停止支持了。clang的那个版本要求只是为了保险起见，没满足的话其实也不一定会出问题。

最后，其实我这个配置就是把purcell的那个fork过来然后删改了一下，原创的东西不多；他的那个配置也可以把evil（也就是你说的vim模式）关掉的，直接在`init.el`里边注释掉对应行即可。

**Comment by minghu6** [comment]
`Ubuntu12..04`只是一个三四年前做pitos等实验搭建的环境，也不做其他用途

原来可以在`init.el`直接注释掉，但是我找不到他的文件里与`evil`有关系的加载语句...

**Comment by minghu6** [comment]
好吧，也许Percell没有evil，只是另一个基于Percell的配置里加入了
`(require 'init-evil)`
