### ISSUE TITLE
A Bug

### ISSUE THREAD

**Issue by minghu6** [xyguo/emacs.d#4]
更新到master配置后，重启emacs加载是出现以下问题
1.
Warning (initialization): An error occurred while loading `/home/xd/.emacs.d/init.el':

File error: http://melpa.milkbox.net/packages/help-fns+-20150909.838.el, Not found

2.
另外最近这次更新前，我发现使用`rgrep`等以来`dired+`的命令时会出现

```
Required dired+ was not provided
```

（但是首先dired+在init.el里是加载了的）

**Comment by xyguo** [comment]
请用下述方法启动，把stacktrace贴上来看看

```
$ emacs --debug-init
```

另外你可以先暂时绕过这个问题：`M-x package-list-packages`打开emacs的包管理器，在里面找`help-fns+`和`dired+`两个包然后手动安装它们。

**Comment by minghu6** [comment]
完整的错误信息，不过那个dired+是没有安装？

Debugger entered--Lisp error: (file-error "http://melpa.milkbox.net/packages/help-fns+-20150909.838.el" "Not found")
  signal(file-error ("http://melpa.milkbox.net/packages/help-fns+-20150909.838.el" "Not found"))
  url-insert-file-contents("http://melpa.milkbox.net/packages/help-fns+-20150909.838.el")
  package-install-from-archive([cl-struct-package-desc help-fns+ (20150909 838) "Extensions to `help-fns.el'." nil single "melpa" nil ((:url . "http://www.emacswiki.org/help-fns+.el") (:keywords "help" "faces" "characters" "packages" "description")) nil])
  mapc(package-install-from-archive ([cl-struct-package-desc help-fns+ (20150909 838) "Extensions to`help-fns.el'." nil single "melpa" nil ((:url . "http://www.emacswiki.org/help-fns+.el") (:keywords "help" "faces" "characters" "packages" "description")) nil]))
  package-download-transaction(([cl-struct-package-desc help-fns+ (20150909 838) "Extensions to `help-fns.el'." nil single "melpa" nil ((:url . "http://www.emacswiki.org/help-fns+.el") (:keywords "help" "faces" "characters" "packages" "description")) nil]))
  package-install(help-fns+)
  (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t)))
  (if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (package-install package) (progn (package-refresh-contents) (require-package package min-version t))))
  require-package(help-fns+)
  eval-buffer(#<buffer  *load*-937528> nil "/home/xd/.emacs.d/lisp/init-editing-utils.el" nil t)  ; Reading at buffer position 142
  load-with-code-conversion("/home/xd/.emacs.d/lisp/init-editing-utils.el" "/home/xd/.emacs.d/lisp/init-editing-utils.el" nil t)
  require(init-editing-utils)
  eval-buffer(#<buffer  *load*> nil "/home/xd/.emacs.d/init.el" nil t)  ; Reading at buffer position 1733
  load-with-code-conversion("/home/xd/.emacs.d/init.el" "/home/xd/.emacs.d/init.el" t t)
  load("/home/xd/.emacs.d/init" t t)
  #[0 "\205\262

**Comment by xyguo** [comment]
我发现你这里自动下载的包版本（20150909）比我自己的（20151215）老很多，能告知一下你的emacs版本吗？谢谢

**Comment by minghu6** [comment]
24.5.1

**Comment by minghu6** [comment]
吐槽一下话说我这里访问melpa的速度真是慢，打开连接可能要几分钟。。。

在用`package-list-packages`安装`help-fns+`时仍旧出现 http://melpa.milkbox.net/packages/help-fns+-20150909.838.el, Not found这样的错误

可能真是源那边的问题。。。

另外安装包`dired+`时确实提示了安装

```
Installed in `~/.emacs.d/elpa/dired+-20151110.921/' (unsigned).
```

事实上那个文件夹也确实存在了
但是从emacs跳转访问时仍然提示之前的Required feature dired+ was not provided

**Comment by xyguo** [comment]
奇怪，按理来说执行package-list-package的时候会自动刷新源的缓存的，为什么你的`dired+`版本也比我的低...你用`package-refresh-contents`试试能把缓存刷新么

**Comment by minghu6** [comment]
不知为什么，我尝试用`package-refresh-contents`，诸如（elpa.gnu.org:80）一些站点的连接一直连接超时，但是之后源似乎确实刷新了。

发现`dired+` ,`help-fns+` 都已经处于obsolete状态（特别对于`dired+`从时间戳上明明只相距了一个月多一点，就废了。。。这种开发风格真是激进）
然后利用elpa更新了所有的插件，删除了obsolete的两个插件（不知道为何更新时没有自动删除）
之后就能顺利加载这两个插件了
