### ISSUE TITLE
when complete cpp code,it occurs "Error runing timer `ac-update-greedy"

### ISSUE THREAD

**Issue by ChyuWei** [xyguo/emacs.d#5]
i have been looking for a emacs.d for myself.
i need to complete cpp.
but it go wrong.don't know why

Error running timer `ac-update-greedy':(error "Invalid argument 3 of opeartion`call-process-region'")

**Comment by xyguo** [comment]
Could you provide more details of the problem, e.g. the full stacktrace? Or some code snippets that reproduce the problem?

**Comment by ChyuWei** [comment]
download you .emacs.d,and lunch emacs,it will download all plugins.
when i write cpp files,it does not work.
just the auto-complete-clang part does not work.
I have seen your .el files,I don not see any about ac-update-greedy.
So i think it may be the problem of the plugin.

I am the green hand.So the error above(it comes up in the minibuffer) is all i can find.
Sorry..

**Comment by minghu6** [comment]
在.emacs.d中rgrep发现以下内容:

```
./elpa/auto-complete-20151227.354/auto-complete.el:1271: (setq ac-timer (run-with-idle-timer ac-delay ac-delay 'ac-update-greedy))))
./elpa/auto-complete-20151227.354/auto-complete.el:1300: (defun ac-update-greedy (&optional force)
./elpa/auto-complete-20151227.354/auto-complete.el:1482: (when (ac-update-greedy t)
```

我猜也许原因只是之前clang没有配置好吧。。。
https://github.com/xyguo/emacs.d#auto-complete-clang

**Comment by ChyuWei** [comment]
I install clang3.7.
I totally copy this .emacs.d to myself
and I changed the path of headeror files to my own..
finall,I change to emacs-ycmd. It works well.

**Comment by minghu6** [comment]
oh

**Comment by xyguo** [comment]
晕，既然你能说中文，早知道就直接说中文了。。。 
`auto-complete-clang`很久没更新了，我怀疑作者已经停止维护了，你们可以考虑用`ac-clang`代替。当然ycmd也是可以的。
最近太忙了，等放假有空了我会把这个配置文件重新整理一下，毕竟好多东西都是一年前写的了。
