### ISSUE TITLE
为什么会重新下载org？

### ISSUE THREAD

**Issue by zhizunbao84** [xyguo/emacs.d#6]
我用的emacs 24.5，用了你这个配置，怎么需要重新下载org，而不是用emacs24.5自带的org呢？

**Comment by xyguo** [comment]
。。我不是很明白你的意思，org-mode肯定是自带的，只是有一些额外的包（例如`org-fstree`）会需要下载，你要是不需要的话可以在`init.el`里把

``` emacslisp
(require 'init-org)
```

这一行注释掉
