### ISSUE TITLE
下载了你的配置把他们放到.emacs目录下，但自动匹配 按table没有进行匹配。不知道为什么？

### ISSUE THREAD

**Issue by zhenchengdezhichi** [xyguo/emacs.d#7]
emacs 版本为24.5.1

**Comment by xyguo** [comment]
首先这些配置文件应该放到`.emacs.d`目录下，不是`.emacs`目录：
```
git clone https://github.com/xyguo/emacs.d.git ~/.emacs.d
```

另外，麻烦你给一些更详细的信息，包括：

1. 上述问题是不是在任何major mode中都出现？因为TAB键在某些mode下面会被重新bind。你可以用`C-h k TAB`查看一下`TAB`键绑定到哪个命令上去了。

2. `auto-complete`模块是否成功载入了？先用debug模式启动Emacs看看有没有出错信息，然后`M-x toggle-debug-on-error`，然后再`M-x auto-complete`试试。
